### ISSUE TITLE
Calculating BPM

### ISSUE THREAD

**Issue by beingmachine** [sparkfun/AD8232_Heart_Rate_Monitor#10]
Hello,
I have https://www.sparkfun.com/products/12650 AD8232 board, from which i can use to plot heart rate PQRST data, however  i can't see code for calculating BPM from the peak like the pulse sensor code do.

How can i calculate BPM with this board

I am getting this output at my Serial Plotter in Arduino..

![screen shot 2017-08-20 at 8 39 11 pm](https://user-images.githubusercontent.com/17064465/29495996-3ea965de-85e7-11e7-929d-b35b9ffe7fa9.png)

Please help

Thank you

**Comment by jawhra** [comment]
Hello,
please I am a student and I am working on the same project could you help me to get the same output , I really need the correct code .
Thanks ,I appreciate your help .

**Comment by beingmachine** [comment]
Hello Jawhra,
Can you post your code.? and what you want to achieve ,Of course i will help you with this.

**Comment by Grahldg** [comment]
BPM calculation example has been added to the Processing sketch [here](https://github.com/sparkfun/AD8232_Heart_Rate_Monitor/blob/master/Software/Heart_Rate_Display_Processing/Heart_Rate_Display/Heart_Rate_Display.pde).

**Comment by guilhermec-costa** [comment]
@Grahldg Do you if this code of the Programming that you sent is compatible with this code:

`void setup() {
// initialize the serial communication:
Serial.begin(9600);
pinMode(10, INPUT); // Setup for leads off detection LO +
pinMode(11, INPUT); // Setup for leads off detection LO -

}

void loop() {

if((digitalRead(10) == 1)||(digitalRead(11) == 1)){
Serial.println('!');
}
else{
// send the value of analog input 0:
Serial.println(analogRead(A1));
}
//Wait for a bit to keep serial data from saturating
delay(10);
}`

**Comment by guilhermec-costa** [comment]
I'm doing a project with the sensor AD8232 and I want to see the BMP, but this kind of sensor doesn't do it. Do you know if there is a way to do it?
