### ISSUE TITLE
Sensor returning only '!'

### ISSUE THREAD

**Issue by MatheusCastilho2** [sparkfun/AD8232_Heart_Rate_Monitor#11]
Hi, everyone.  I need this project for 3 days....

In condition below always return '!'

if ((digitalRead (10) == 1) || (digitalRead (11) == 1)) 
  { Serial.println ('!'); }
  else 
  {
    Serial.println(analogRead (A0));

    } 
    delay (1); 

How I resolve this?

**Comment by harpekar** [comment]
I have filed an issue to fix this (#12).

**Comment by Grahldg** [comment]
I was unable to duplicate this issue with the circuit described in the hookup guide.  If you are having issues in the future and need more immediate assistance, please contact our [Technical Support Team](https://www.sparkfun.com/technical_assistance).
