### ISSUE TITLE
SDN Pin missing from initialization

### ISSUE THREAD

**Issue by harpekar** [sparkfun/AD8232_Heart_Rate_Monitor#12]
The SDN pin must be pulled high in order for the board to not be put into Shutdown mode, as stated in the [datasheet](http://www.analog.com/media/en/technical-documentation/data-sheets/AD8232.pdf) on page 19. 

Recommend adding 

```c++
pinMode(SDNBAR, INPUT);
digitalWrite(SDNBAR, HIGH);
```

in `setup()`, with SDNBAR being the Arduino pin that indexes SDN.

**Comment by vredzhepov** [comment]
The SDN pin has been already pulled up by R15 so there's no need to pull it up in code.

**Comment by Grahldg** [comment]
Thank you for your suggestion.  This does not seem to affect the functionality of the circuit described in the hookup guide.  If you are still having issues with this and have further questions, please contact our [Technical Support Team](https://www.sparkfun.com/technical_assistance).
