### ISSUE TITLE
Sampling rate

### ISSUE THREAD

**Issue by DominiqueMakowski** [sparkfun/AD8232_Heart_Rate_Monitor#14]
Hey, I do have a question and didn't find the answer in the data sheet.

What is the default / maximum sampling rate with which we can acquire ECG with this?

Thanks

**Comment by Fieryfire** [comment]
You essentially find the bandwidth of the ECG signal and multiply by 10. So
you have 40Hz bandwidth. And with 400Hz set as sampling rate. You should be
good to go

On Thu, Aug 2, 2018 at 4:08 PM, Dominique Makowski <notifications@github.com

**Comment by Fieryfire** [comment]
The AD8232 is only a signal conditioner. The output from it is analog. It
is upto you to use a micro controller with an ADC to be able to sample the
analog data
For ex. using an arduino can get the job done

On Thu, Aug 2, 2018 at 6:23 PM, Dominique Makowski <notifications@github.com

**Comment by DominiqueMakowski** [comment]
Ok i got it  :)
