### ISSUE TITLE
Helpp

### ISSUE THREAD

**Issue by ramapsam** [sparkfun/AD8232_Heart_Rate_Monitor#15]
why this error when i'm uploaded??

import processing.serial.*;

Serial myPort;        // The serial port

**Comment by Grahldg** [comment]
Hi @ramapsam ,

Sorry for the delayed response.  It's hard to know what could be causing this problem without further information.  If you could contact our [Technical Assistance Team](https://www.sparkfun.com/technical_assistance) they should be able to gather information needed and help you solve this problem.
