### ISSUE TITLE
EKG sheild error question

### ISSUE THREAD

**Issue by biovet** [sparkfun/AD8232_Heart_Rate_Monitor#5]
I am new to arduino and have been attempting to use the EKG shield and have uploaded the sketch you have her but keep getting error messages when I attempt to verify.  'serailEvent" declared void What am I missing?

**Comment by z3t0** [comment]
It seems they are two different sketches for different systems
You definitely want to use [this](https://github.com/sparkfun/AD8232_Heart_Rate_Monitor/blob/master/Software/Heart_Rate_Display_Arduino/Heart_Rate_Display_Arduino.ino) for the Arduino Uno

**Comment by z3t0** [comment]
The reason for getting those errors are because that file is not for Arduino (atleast not directly)

**Comment by z3t0** [comment]
Also note that an arduino can hold no MORE than one sketch at a time so at no point in time should you ever need to use two sketches for any purpose because it simply doesnt work like that

**Comment by ToniCorinne** [comment]
Please read the hookup guide here: https://learn.sparkfun.com/tutorials/ad8232-heart-rate-monitor-hookup-guide#uploading-the-sketch-and-connecting-with-processing. 

This explains why there are two different sketches. The .pde file is actually for Processing, not Arduino (though the old Arduino IDE did use the same file extension).
