### ISSUE TITLE
Not compatible with Processing 3.2.4

### ISSUE THREAD

**Issue by SSJJYY** [sparkfun/AD8232_Heart_Rate_Monitor#7]
These codes cannot be operated on Processing 3.2.4 successfully. Only can on Processing 2.2.1.
Problems happens when you run it, it shows a blank display screen.
Can you update codes for version 3.2.4? 
Thank you a lot.

**Comment by paulio23** [comment]
Second that.

**Comment by Fieryfire** [comment]
third that

**Comment by mctosimaitb** [comment]
agree :)

**Comment by ShubhaM220** [comment]
why is it not working on processing 3.2.4 ??

**Comment by rubueh** [comment]
Ive made a pull request for the updated version of the heart rate monitor but have not gotten a response from Sparkfun. Here are some proposed changes for the code of the heart rate monitor, the old code could only function in the second version of Processing. The proposed changes now work for the newest version (3.3.2). I figured other individuals could benefit from this and help them get their project done faster and with a lot less headaches.

Side-Note 
The only hiccup I encountered in modifying the code and comparing it to the old one's readings was that when it is supposed to be flat-line there is a negative charge that is registered, which was not there when run in Processing v2.
-RKB

Also let me know how it works for you.

//-----------------------------------New Code for Processing 3.2.+------------------//

/*
*  All rights reserved to the original creators.
*/

import processing.serial.*;

Serial myPort;
int xPos = 1;
float height_old = 0;
float height_new = 0;
float inByte = 0;


void setup () {
  //Window Size
  size(1080, 500);        

  // List serial ports
  println(Serial.list());
  myPort = new Serial(this, Serial.list()[0], 9600);
  myPort.bufferUntil('\n');
  
  //Background
  background(255);
  
  fill(color(0,0,0));
  text("Heart Rate Monitor v1.0", 10, 10);
}


void draw () {
       
     inByte = map(inByte, 0, 1023, 0, height);
     height_new = height - inByte; 
     line(xPos - 1, height_old, xPos, height_new);
     height_old = height_new;
    
      if (xPos >= width) {
        xPos = 0;
        background(255);
      } 
      else {
        xPos++;
      }
}


void serialEvent (Serial myPort) {
  // get the ASCII string:
  String inString = myPort.readStringUntil('\n');

  if (inString != null) {
    // trim off any whitespace:
    inString = trim(inString);

    if (inString.equals("!")) { 
      stroke(0, 0, 255);
      inByte = 512;
    }
    else {
      stroke(255, 0, 0);
      inByte = float(inString); 
     }
  }
}

**Comment by rubueh** [comment]
`//-----------------------------------New Code for Processing 3.2.+------------------//

/*
*  All rights reserved to the original creators.
*/

import processing.serial.*;

Serial myPort;
int xPos = 1;
float height_old = 0;
float height_new = 0;
float inByte = 0;


void setup () {
  //Window Size
  size(1080, 500);        

  // List serial ports
  println(Serial.list());
  myPort = new Serial(this, Serial.list()[0], 9600);
  myPort.bufferUntil('\n');
  
  //Background
  background(255);
  
  fill(color(0,0,0));
  text("Heart Rate Monitor v1.0", 10, 10);
}


void draw () {
       
     inByte = map(inByte, 0, 1023, 0, height);
     height_new = height - inByte; 
     line(xPos - 1, height_old, xPos, height_new);
     height_old = height_new;
    
      if (xPos >= width) {
        xPos = 0;
        background(255);
      } 
      else {
        xPos++;
      }
}


void serialEvent (Serial myPort) {
  // get the ASCII string:
  String inString = myPort.readStringUntil('\n');

  if (inString != null) {
    // trim off any whitespace:
    inString = trim(inString);

    if (inString.equals("!")) { 
      stroke(0, 0, 255);
      inByte = 512;
    }
    else {
      stroke(255, 0, 0);
      inByte = float(inString); 
     }
  }
}`

**Comment by XDTZ** [comment]
@rubueh I felt very lucky finishing my wiring and immediately finding your fix no longer than a day after you posted!
The code does work for me. However it seems serial plotter produce graph more clear than this. Thanks anyway!

**Comment by rubueh** [comment]
@XDTZ I am glad the code was able to help and for getting back on how it works for you. If I can recommend something, while working on the wiring and programming I noticed my data was wonky while I had my charger plugged in to my laptop during testing. I then removed the charger and voila, it worked. So just double check your wiring or if you have an external power source that may be causing the interference, see if you can mend it. You may not need any extra items. Best of luck though!

**Comment by marziacescon** [comment]
Hi!

I'm still having the blank screen problem, despite I'm running the fixed script proposed here..I don't know what I'm doing wrong! I feel discouraged. Any chance I could get any help here?

Thanks heaps!
![screen shot 2017-05-31 at 11 49 28](https://cloud.githubusercontent.com/assets/19808421/26627291/371e6f58-45fa-11e7-984b-0b4505d94f87.jpg)

**Comment by Fieryfire** [comment]
Hi,

Do you see, if there is transmission through serial monitor?

**Comment by marziacescon** [comment]
Hi! Thanks for your prompt reply! I'm new to this so not experienced at all!

How do you see if you get transmission? I mean: I can plot things on the
screen if I want to..just I can't visualize the ECG...

Marzia

**Comment by marziacescon** [comment]
Hi,

got it. I tried to modify that in order to allow communication, but nothing
happens still...

The ports are the following:

/dev/cu.Bluetooth-Incoming-Port /dev/cu.Bluetooth-Modem
/dev/cu.Cons-SerialPort
/dev/cu.usbserial-A904MJ7W /dev/tty.Bluetooth-Incoming-Port
/dev/tty.Bluetooth-Modem
/dev/tty.Cons-SerialPort /dev/tty.usbserial-A904MJ7W

Anything wrong in there?

Thanks again!

Marzia

**Comment by marziacescon** [comment]
When I change port, I get the following error message (attached
![screen shot 2017-06-01 at 10 20 35](https://cloud.githubusercontent.com/assets/19808421/26670947/0db9b14e-46b4-11e7-9c70-ba3dea6869df.jpg)
)

**Comment by rubueh** [comment]
@marziacescon 
Hmmm first try checking all your wiring is correct, connect the ECG leads, run the sketch and see if can get a signal (even if its ugly one) from the leads just to make sure they are making contact and the wiring is correctly routing the signals. The other problem may be that if you have the Arduino program open, it is taking control of that port first to communicate with the Arduino itself. If so, just exit out, if not try to see what is taking up the communications port channel.

**Comment by rubueh** [comment]
@marziacescon 
I just realized your COM list simply looks different, so for every `/dev/` item you see, that is a different port. So the port you are wanting to communicate through may actually be `Serial.list()[5]` .

**Comment by Fieryfire** [comment]
I think it says port busy because you are opening the serial monitor from
the arduino IDE as well. Let go of the the serial monitor and just let the
code from processing run

**Comment by njay96** [comment]
![ggh](https://cloud.githubusercontent.com/assets/29169105/26757861/7a938266-48f5-11e7-990e-7a1dca07ce7f.png)
@rubueh im so happy when ur code work for me, thank you. but, my result so noisy. how to calibrate it? or it because wrong placement of the sensor. i so confused if it by sensor placement, im affraid if i not correctly put that sensor. sorry my english so bad. anyway, thank you!

**Comment by marziacescon** [comment]
Hi!

Thank you for your suggestions.

I'm afraid to say, I still have the same problem.

* I'm letting the code from Processing only run (no Arduino)
* I have identified the correct port, i.e., I don't get the "port busy"
message anymore.

But I still have only a blank screen...like no signals is going through.
I've check the wiring as well and it seems correct...What shall I do now?

Thank you in advance!

Marzia

**Comment by marziacescon** [comment]
I'm thinking that maybe the AD8232 is faulty....

Marzia

**Comment by rubueh** [comment]
@marziacescon 

I'm thinking it might be as well, if not ask someone else to double check everything as a last resort and no problem, I really do hope you can get it to work.

**Comment by marziacescon** [comment]
I do hope it as well.

I got already someone checking the wiring : it seems all is good. So i
think the sensor might be faulty.

**Comment by Fieryfire** [comment]
Does the serial port from the arduino IDE run any values to the the monitor?

**Comment by marziacescon** [comment]
Actually not. No numbers. It's so frustrating!

Marzia

**Comment by Fieryfire** [comment]
Using a multimeter, are you able to get any sort of readings from the
analog output?

**Comment by marziacescon** [comment]
Hi!

I'm going to borrow one as soon as I can.

In the meantime, I checked if the Arduino and Processing were able to
communicate. I used the following scripts:

***arduino***
**************
void setup()
{
//initialize serial communications at a 9600 baud rate
Serial.begin(9600);
}

void loop()
{
//send 'Hello, world!' over the serial port
Serial.println("Hello, world!");
//wait 100 milliseconds so we don't drive ourselves crazy
delay(100);
}

***processing***
******************
import processing.serial.*;
Serial myPort;  // Create object from Serial class
String val;     // Data received from the serial port
void setup()
{
  // I know that the first port in the serial list on my mac
  // is Serial.list()[0].
  // On Windows machines, this generally opens COM1.
  // Open whatever port is the one you're using.
  String portName = Serial.list()[0]; //change the 0 to a 1 or 2 etc. to
match your port
  myPort = new Serial(this, portName, 9600);
}
void draw()
{
  if ( myPort.available() > 0)
  {  // If data is available,
  val = myPort.readStringUntil('\n');         // read it and store it in val
  }
println(val); //print it out in the console
}

****

And what I get out printed in the console is:
null
null
null
...

Do it seems that the Arduino is not talking to processing..maybe why I
don't get any signal displayed. I swear, I followed the instructions
literally and I'm not getting it to work! I thought I was going to learn
things, instead I'm getting demoralised.



Marzia

**Comment by marziacescon** [comment]
And this is what I get on the serial monitor
![screen shot 2017-06-05 at 22 45 29](https://cloud.githubusercontent.com/assets/19808421/26802476/e89abde6-4a40-11e7-9e90-afec31a3d58d.jpg)

**Comment by Fieryfire** [comment]
Lets trouble shoot it step by step, the serial terminal from the arduino
IDE shows you the above results? am i correct? it means there is something
wrong from the arduino side itself.

1)Try the code using another system, windows (preferably?)
2)set the port of the arduino to be the same as the one in serial monitor.
3) Show more screenshots on your setup and lets see whats going.

**Comment by marziacescon** [comment]
Let's do it. I really appreciate your patience! Thanks.

So:
1) I have tried the code on a Windows machine
2) The port of the Arduino is the same of the serial monitor, i.e., COM3 (see pics)
3) I am attaching some pics of the results and the setup.

Hopefully we'll be able to sort things out.
![pic1](https://cloud.githubusercontent.com/assets/19808421/26827381/48b16a5a-4abd-11e7-9612-8011e7a867ff.jpg)
![pic2](https://cloud.githubusercontent.com/assets/19808421/26827385/4f2235b8-4abd-11e7-985e-91e662869d9b.jpg)
![pic3](https://cloud.githubusercontent.com/assets/19808421/26827390/54146302-4abd-11e7-89df-9c1fad78e230.jpg)
![pic8](https://cloud.githubusercontent.com/assets/19808421/26827394/59b2b606-4abd-11e7-8ba5-0bf235e9b4e4.jpg)
![pic7](https://cloud.githubusercontent.com/assets/19808421/26827400/604b0ffe-4abd-11e7-8cd9-50b80025ad2e.jpg)
![pic6](https://cloud.githubusercontent.com/assets/19808421/26827403/64d5be2a-4abd-11e7-9cae-0e334e2c2ddc.jpg)
![pic5](https://cloud.githubusercontent.com/assets/19808421/26827407/68318df6-4abd-11e7-8789-aa20129faa95.jpg)
![pic4](https://cloud.githubusercontent.com/assets/19808421/26827408/6b9609d6-4abd-11e7-885a-872ac8056e9a.jpg)

**Comment by Fieryfire** [comment]
1) Try just outputing the hello world alone to serial. Show the result. If
the basic hello world serial out fails to work. You should first
troubleshoot this stage.
2) From the circuit wiring . Make sure to connect output of AD8232 to A0 of
arduino board. Also is the arduino a 3.3v or a 5v??? Because the AD8232 is
not 5V tolerant.
3) Make sure that when the FTDI is connected in the right direction, VCC
->VCC GND to GND,etc... Share the the pin layout of the arduino you are
using.

**Comment by marziacescon** [comment]
Hi!

So, I managed to solve the above mentioned issues. Now I have the Arduino
up and running and communicating with Processing.

The only thing now is that it's transmitting a sequence of '1023'
corresponding to a flat red line. I haven't investigated this issue yet..so
any help would be appreciated!!!! Thanks!

Marzia

**Comment by Fieryfire** [comment]
Can you explain, what was the problem before? it would be better if you
mentioned the reason of the issue so that it will be helpful for others who
read the forum.

The value 1023 means the adc is sending saturated values. The output is at
3.3v, You would normally expect values if i remember correctly at about
half of that. at 1.1V while you have the electrodes on, use a multimeter to
read the output.

**Comment by marziacescon** [comment]
Hi! 

I see. I understand that 1023 corresponds to saturated output but I don't understand why...I have checked the soldering and the connections: all good. Leads off detection is working, but I don't get why the output stays at 3.3V whenever I have the three electrodes on. Any guess? Would you have a suggestion on how to solve this issue? 

Thank you so much in advance!!

**Comment by Fieryfire** [comment]
1023, is the converted value of 3.3V output from the AD8235. The Arduino
ADC is working at 10-bit conversion rate. 2^10 gives 1024. Hence the value.

For why the value is saturated. Are you placing the two electrodes in close
proximity? the 3rd electrode is to take out the 50Hz noise from the power
lines (if i remember correctly)

**Comment by marziacescon** [comment]
Actually, I'm putting them on the wrists. And I get only a flat line corresponding to 1023...I can't solve it! Any help would be much more than welcome!

**Comment by Fieryfire** [comment]
It could be several reasons. But first connect your analog output to an
oscilloscope. Application of salt water over the wrists should increase
conductivity between the skin and the electrodes. I personally havent tried
with the wrists. In my personal test last year, i had place the electrodes
in close proximity near to the heart and the third electrode right below.
Can you try this set up and see if you are able to observe any difference?

**Comment by Grahldg** [comment]
@rubueh  thank you for your insights.  The latest update was tested compatible with Processing 2.2 and 3.3.7.
