### ISSUE TITLE
Classify Wave into PQRST

### ISSUE THREAD

**Issue by mctosimaitb** [sparkfun/AD8232_Heart_Rate_Monitor#8]
Hi, i just have an idea. What if the wave is classified into PQRST wave intervals, such as 'p wave', 'QRS Complex', and 't wave', etc. The goal is that the system can recognize that there are abnormalities of the heart such as heart attacks. Do you have a way to do that?

**Comment by Fieryfire** [comment]
Hi Yes, this can be done by adding elements to the software. But do realize
that this isnt completely medically accurate. and we would need to use
medical grade equipments. This is more for hobbyists to play around with
heart rates

**Comment by mctosimaitb** [comment]
could u tell me, what is the lowest number and the highest number that displayed in serial monitor when using ad8232 ?

I just want to imagine how to implement those number into ecg block paper..

**Comment by Grahldg** [comment]
Hello mctosimaitb,

These values can vary significantly depending on where the electrodes are connected and from person to person.  It may be possible to normalize the data and use algorithms to identify different wave forms, but that is beyond the scope of the example provided here.  You might find the [datasheet](https://cdn.sparkfun.com/datasheets/Sensors/Biometric/AD8232.pdf) helpful.  In addition our [Technical Support Team](https://www.sparkfun.com/technical_assistance) can help with any further questions you may have.

Thanks,
Sam
